"""Number-provenance enforcement for `docs/TECHNICAL.md` and `README.md`
(Phase 10) -- the two hand-written documents in this project, as opposed to
`docs/RESULTS.md` (code-generated by `eval/report.py` via pure f-string
interpolation, enforced separately by
`tests/test_report.py::test_every_number_in_results_md_traces_to_metrics_json`).

**Why this is a NEW, narrowly-scoped test rather than an extension of
`tests/test_report.py`**: that module's `_flatten_numbers`/`_extract_doc_numbers`/
`_traces_to_source` helpers compare an in-memory, fixture-generated markdown
string against an in-memory, fixture-generated (small, fast-config) metrics
payload -- deliberately smaller-scale test data than the REAL committed dataset
`docs/TECHNICAL.md` and `README.md` actually describe in prose. Reusing those
helpers directly would require plumbing the real, on-disk
`results/metrics.json` through a fixture-oriented test module built around a
different (in-memory, per-test-run) data source -- a bigger and less clean
change than duplicating the same ~20 lines of pure regex/matching logic here,
pointed at the real on-disk artifacts these two hand-written docs must actually
trace to.

**Why the source pool is wider here than `tests/test_report.py`'s**: the task's
own hard rule for this phase is that every number in `docs/TECHNICAL.md`/
`README.md` must trace to `results/metrics.json`, `results/scenarios/*.json`,
`docs/RESULTS.md`, OR `docs/DATA_CARD.md`'s already-verified figures -- a
deliberately wider set than `docs/RESULTS.md`'s own stricter
"metrics.json only" rule, because `docs/RESULTS.md` is 100% code-generated from
`results/metrics.json` (so nothing else could ever be a legitimate source for
it), whereas `docs/TECHNICAL.md`/`README.md` are hand-written prose that
legitimately cites dataset-scale facts (POI/traveler/trip counts, channel
quotas, wall-clock timings) that live only in `docs/DATA_CARD.md`'s prose or in
`spec.md`'s own literal design text (channel counts, archetype counts, quota
tables) -- never computed pipeline output, but real, citable project facts
nonetheless. `spec.md` is included as a source pool for exactly this reason:
structural/design facts (quota values, channel/archetype/system counts) are
spec.md's own literal text, not something either new doc invents."""

from __future__ import annotations

import json
import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]

_NUMBER_RE = re.compile(r"[-+]?\d*\.\d+|[-+]?\d+")
_SECTION_REF_RE = re.compile(r"section \d+(\.\d+)?", re.IGNORECASE)

# Mirrors tests/test_report.py's own `_STRUCTURAL_ALLOWLIST` exactly (same
# target thresholds from spec.md section 11.10, same small structural-index
# range) -- these are either literal spec.md targets or small structural
# counts (deciles/ranks/section numbers), never pipeline output.
_STRUCTURAL_ALLOWLIST: frozenset[float] = frozenset(
    {
        0.05,
        0.25,
        0.40,
        0.5,
        0.7,
        0.8,
        0.9,
        1.0,
        2.0,
        2.5,
        5.0,
        10.0,
        15.0,
        20.0,
        50.0,
        90.0,
        97.5,
        100.0,
        250.0,
        0.01,
        0.6,
    }
    | {float(i) for i in range(0, 12)}
)

_SOURCE_DOC_NAMES = ("docs/RESULTS.md", "docs/DATA_CARD.md", "spec.md")
_TARGET_DOC_NAMES = (
    "docs/TECHNICAL_SUMMARY.md",
    "docs/TECHNICAL.md",
    "README.md",
    "docs/REQUIREMENTS.md",
)


def _flatten_numbers(obj: object, out: list[float]) -> None:
    if isinstance(obj, bool):
        return
    if isinstance(obj, int | float):
        out.append(float(obj))
    elif isinstance(obj, dict):
        for v in obj.values():
            _flatten_numbers(v, out)
    elif isinstance(obj, list):
        for v in obj:
            _flatten_numbers(v, out)


def _extract_numbers(text: str) -> list[float]:
    cleaned = _SECTION_REF_RE.sub("", text)
    values: list[float] = []
    for match in _NUMBER_RE.finditer(cleaned):
        try:
            values.append(float(match.group()))
        except ValueError:
            continue
    return values


def _relative_lift_percentages(source_values: list[float]) -> list[float]:
    """Same derived-quantity allowance as `tests/test_report.py`: `(a/b - 1) * 100`
    for ordered pairs of small positive source leaves, covering
    `docs/RESULTS.md`'s own "NDCG@10 vs popularity" relative-lift phrasing
    reproduced in prose here."""
    small_positive = [s for s in source_values if 0.0 < s <= 5.0]
    out: list[float] = []
    for a in small_positive:
        for b in small_positive:
            if b != 0.0:
                out.append((a / b - 1.0) * 100.0)
    return out


def _traces_to_source(value: float, source_values: list[float], ratio_pairs: list[float]) -> bool:
    raw_tol = 0.0005
    pct_tol = 0.06
    if any(abs(value - s) < raw_tol for s in _STRUCTURAL_ALLOWLIST):
        return True
    for s in source_values:
        if abs(value - s) < raw_tol:
            return True
        if abs(value - s * 100.0) < pct_tol:
            return True
        if abs(value + s) < raw_tol:
            return True
    return any(abs(value - r) < pct_tol for r in ratio_pairs)


def _build_source_pool() -> list[float]:
    """Every numeric leaf in `results/metrics.json` and `results/scenarios/*.json`
    (the REAL, on-disk, committed artifacts -- not a test fixture), plus every
    numeric token appearing anywhere in `docs/RESULTS.md`, `docs/DATA_CARD.md`,
    and `spec.md`'s own text (per this module's docstring: legitimate citable
    project facts for hand-written prose, even when not pipeline output)."""
    values: list[float] = []
    metrics_path = REPO_ROOT / "results" / "metrics.json"
    metrics = json.loads(metrics_path.read_text(encoding="utf-8"))
    _flatten_numbers(metrics, values)

    scenarios_dir = REPO_ROOT / "results" / "scenarios"
    for scenario_path in sorted(scenarios_dir.glob("*.json")):
        _flatten_numbers(json.loads(scenario_path.read_text(encoding="utf-8")), values)

    for name in _SOURCE_DOC_NAMES:
        text = (REPO_ROOT / name).read_text(encoding="utf-8")
        values.extend(_extract_numbers(text))

    return values


def test_metrics_json_and_scenarios_artifacts_exist() -> None:
    """Sanity precondition: the source-of-truth artifacts this test cross-checks
    against must actually be present and non-trivial, or a silent-pass (empty
    source pool -> everything "traces" vacuously) would defeat the whole point."""
    metrics_path = REPO_ROOT / "results" / "metrics.json"
    assert metrics_path.exists(), "results/metrics.json missing -- run `poi_rank.cli evaluate`"
    metrics = json.loads(metrics_path.read_text(encoding="utf-8"))
    assert "lodo" in metrics, (
        "results/metrics.json is missing the 'lodo' key -- run `poi_rank.cli lodo` "
        "after `evaluate` (docs/DATA_CARD.md #85's documented read-modify-write "
        "order dependency: a later `evaluate` call silently wipes this key)"
    )
    scenarios_dir = REPO_ROOT / "results" / "scenarios"
    scenario_files = list(scenarios_dir.glob("*.json"))
    assert len(scenario_files) >= 4, "results/scenarios/*.json missing -- run `cli scenarios`"


def test_every_number_in_technical_md_and_readme_traces_to_a_real_artifact() -> None:
    """The actual enforcement mechanism for this phase's hard rule ("no number in
    docs/TECHNICAL.md or README.md may be hand-typed without tracing to a real
    project artifact") -- a real grep-and-cross-check against the live,
    committed `results/metrics.json` / `results/scenarios/*.json` /
    `docs/RESULTS.md` / `docs/DATA_CARD.md` / `spec.md`, not a manual promise."""
    source_values = _build_source_pool()
    ratio_pairs = _relative_lift_percentages(source_values)

    for doc_name in _TARGET_DOC_NAMES:
        doc_path = REPO_ROOT / doc_name
        assert doc_path.exists(), f"{doc_name} does not exist"
        text = doc_path.read_text(encoding="utf-8")
        doc_numbers = _extract_numbers(text)
        untraceable = [
            n for n in doc_numbers if not _traces_to_source(n, source_values, ratio_pairs)
        ]
        assert not untraceable, (
            f"{len(untraceable)} number(s) in {doc_name} do not trace to results/metrics.json, "
            f"results/scenarios/*.json, docs/RESULTS.md, docs/DATA_CARD.md, or spec.md "
            f"(first 20): {untraceable[:20]}"
        )
